content = [
    "const { app, BrowserWindow } = require('electron');",
    "const { spawn } = require('child_process');",
    "const path = require('path');",
    "const fs = require('fs');",
    "",
    "let mainWindow;",
    "let backendProcess;",
    "",
    "const API_URL = 'https://phonesoftware-standalone.onrender.com';",
    "const PORT = 8000;",
    "",
    "function startBackend() {",
    "  const backendExe = path.join(process.resourcesPath, 'backend', 'server.exe');",
    "  if (fs.existsSync(backendExe)) {",
    "    backendProcess = spawn(backendExe, [], {",
    "      env: { ...process.env,",
    "        PORT: String(PORT),",
    "        MONGO_URL: 'mongodb+srv://urimi1806:1806@cluster0.3jzigcr.mongodb.net/?appName=Cluster0',",
    "        JWT_SECRET: 'phonesoftware_secret_key',",
    "        DB_NAME: 'phonesoftware_db'",
    "      }",
    "    });",
    "    console.log('Backend started from:', backendExe);",
    "  } else {",
    "    console.log('Using remote backend:', API_URL);",
    "  }",
    "}",
    "",
    "function createWindow() {",
    "  mainWindow = new BrowserWindow({",
    "    width: 1280,",
    "    height: 800,",
    "    minWidth: 1024,",
    "    minHeight: 600,",
    "    icon: path.join(__dirname, 'assets', 'icon.ico'),",
    "    webPreferences: {",
    "      nodeIntegration: false,",
    "      contextIsolation: true,",
    "      webSecurity: false",
    "    },",
    "    title: 'PhoneSoftware',",
    "    show: false",
    "  });",
    "",
    "  mainWindow.setMenuBarVisibility(false);",
    "",
    "  const indexPath = path.join(__dirname, 'build', 'index.html');",
    "  mainWindow.loadFile(indexPath);",
    "",
    "  mainWindow.once('ready-to-show', () => {",
    "    mainWindow.show();",
    "    mainWindow.maximize();",
    "  });",
    "",
    "  mainWindow.webContents.on('did-fail-load', (e, code, desc) => {",
    "    console.error('Load failed:', desc);",
    "    mainWindow.loadFile(indexPath);",
    "  });",
    "}",
    "",
    "app.whenReady().then(() => {",
    "  startBackend();",
    "  createWindow();",
    "});",
    "",
    "app.on('before-quit', () => {",
    "  if (backendProcess) backendProcess.kill();",
    "});",
    "",
    "app.on('window-all-closed', () => {",
    "  if (process.platform !== 'darwin') app.quit();",
    "});",
]
with open('frontend/electron.js', 'w', encoding='utf-8') as f:
    f.write('\n'.join(content))
print("electron.js updated!")
