lines = [
    '"""PhoneSoftware Tenant Management Routes"""',
    'from fastapi import APIRouter, HTTPException, Request',
    'from datetime import datetime, timezone, timedelta',
    'import uuid, os as _os, database as _db_module',
    'import jwt as _jwt',
    'from .database import ps_tenants, ps_users, ps_repairs',
    'from .models import PSTenantCreate, PSTenantUpdate, PSUserCreate, PSUserRole, PSTenantStatus',
    'from auth import hash_password',
    '',
    'router = APIRouter(prefix="/phonesoftware/tenants", tags=["PhoneSoftware Tenants"])',
    '',
    '',
    'async def _auth(request: Request):',
    '    h = request.headers.get("Authorization", "")',
    '    if not h.startswith("Bearer "):',
    '        raise HTTPException(status_code=401, detail="Token mungon")',
    '    try:',
    '        p = _jwt.decode(h.split(" ")[1], _os.environ.get("JWT_SECRET","phonesoftware_secret_key"), algorithms=["HS256"])',
    '        uid = p.get("sub") or p.get("user_id") or p.get("id")',
    '        u = await ps_users.find_one({"id": uid},{"_id":0})',
    '        if not u:',
    '            u = await _db_module.pos_users.find_one({"id": uid},{"_id":0})',
    '        if not u:',
    '            raise HTTPException(status_code=401, detail="User not found")',
    '        if u.get("role") != "super_admin":',
    '            raise HTTPException(status_code=403, detail="Super Admin only")',
    '        return u',
    '    except HTTPException:',
    '        raise',
    '    except Exception as e:',
    '        raise HTTPException(status_code=401, detail=str(e))',
    '',
    '',
    '@router.get("")',
    'async def get_tenants(request: Request):',
    '    await _auth(request)',
    '    ts = await ps_tenants.find({},{"_id":0}).sort("created_at",-1).to_list(1000)',
    '    for t in ts:',
    '        t["users_count"] = await ps_users.count_documents({"tenant_id":t["id"]})',
    '        t["repairs_count"] = await ps_repairs.count_documents({"tenant_id":t["id"]})',
    '    return ts',
    '',
    '',
    '@router.post("")',
    'async def create_tenant(tenant: PSTenantCreate, request: Request):',
    '    await _auth(request)',
    '    if await ps_tenants.find_one({"name":tenant.name.lower()}):',
    '        raise HTTPException(status_code=400, detail="Emri ekziston")',
    '    if await ps_tenants.find_one({"email":tenant.email.lower()}):',
    '        raise HTTPException(status_code=400, detail="Email ekziston")',
    '    months = getattr(tenant,"subscription_months",1)',
    '    doc = {"id":str(uuid.uuid4()),"name":tenant.name.lower(),"company_name":tenant.company_name,',
    '        "email":tenant.email.lower(),"phone":getattr(tenant,"phone",None),',
    '        "address":getattr(tenant,"address",None),"city":getattr(tenant,"city",None),',
    '        "logo_url":getattr(tenant,"logo_url",None),',
    '        "primary_color":getattr(tenant,"primary_color","#00BCD4"),',
    '        "secondary_color":getattr(tenant,"secondary_color","#263238"),',
    '        "status":PSTenantStatus.ACTIVE if months>1 else PSTenantStatus.TRIAL,',
    '        "subscription_expires":(datetime.now(timezone.utc)+timedelta(days=30*months)).isoformat(),',
    '        "created_at":datetime.now(timezone.utc).isoformat()}',
    '    await ps_tenants.insert_one(doc)',
    '    doc.pop("_id",None)',
    '    return doc',
    '',
    '',
    '@router.get("/{tenant_id}")',
    'async def get_tenant(tenant_id: str, request: Request):',
    '    await _auth(request)',
    '    t = await ps_tenants.find_one({"id":tenant_id},{"_id":0})',
    '    if not t:',
    '        raise HTTPException(status_code=404, detail="Firma nuk u gjet")',
    '    return t',
    '',
    '',
    '@router.put("/{tenant_id}")',
    'async def update_tenant(tenant_id: str, update: PSTenantUpdate, request: Request):',
    '    await _auth(request)',
    '    if not await ps_tenants.find_one({"id":tenant_id}):',
    '        raise HTTPException(status_code=404, detail="Firma nuk u gjet")',
    '    data = {k:v for k,v in update.dict().items() if v is not None}',
    '    if data:',
    '        await ps_tenants.update_one({"id":tenant_id},{"$set":data})',
    '    return await ps_tenants.find_one({"id":tenant_id},{"_id":0})',
    '',
    '',
    '@router.delete("/{tenant_id}")',
    'async def delete_tenant(tenant_id: str, request: Request):',
    '    await _auth(request)',
    '    if not await ps_tenants.find_one({"id":tenant_id}):',
    '        raise HTTPException(status_code=404, detail="Firma nuk u gjet")',
    '    await ps_tenants.delete_one({"id":tenant_id})',
    '    await ps_users.delete_many({"tenant_id":tenant_id})',
    '    await ps_repairs.delete_many({"tenant_id":tenant_id})',
    '    return {"message":"Firma u fshi"}',
    '',
    '',
    '@router.get("/{tenant_id}/users")',
    'async def get_users(tenant_id: str, request: Request):',
    '    await _auth(request)',
    '    return await ps_users.find({"tenant_id":tenant_id},{"_id":0,"password_hash":0}).to_list(1000)',
    '',
    '',
    '@router.post("/{tenant_id}/users")',
    'async def create_user(tenant_id: str, user_data: PSUserCreate, request: Request):',
    '    await _auth(request)',
    '    if not await ps_tenants.find_one({"id":tenant_id}):',
    '        raise HTTPException(status_code=404, detail="Firma nuk u gjet")',
    '    if await ps_users.find_one({"username":user_data.username,"tenant_id":tenant_id}):',
    '        raise HTTPException(status_code=400, detail="Username ekziston")',
    '    doc = {"id":str(uuid.uuid4()),"tenant_id":tenant_id,"username":user_data.username,',
    '        "full_name":getattr(user_data,"full_name",user_data.username),',
    '        "role":getattr(user_data,"role",PSUserRole.ADMIN),',
    '        "password_hash":hash_password(user_data.password),"is_active":True,',
    '        "created_at":datetime.now(timezone.utc).isoformat()}',
    '    await ps_users.insert_one(doc)',
    '    doc.pop("_id",None)',
    '    doc.pop("password_hash",None)',
    '    return doc',
    '',
    '',
    '@router.delete("/{tenant_id}/users/{user_id}")',
    'async def delete_user(tenant_id: str, user_id: str, request: Request):',
    '    await _auth(request)',
    '    if not await ps_users.find_one({"id":user_id,"tenant_id":tenant_id}):',
    '        raise HTTPException(status_code=404, detail="User nuk u gjet")',
    '    await ps_users.delete_one({"id":user_id,"tenant_id":tenant_id})',
    '    return {"message":"Perdoruesi u fshi"}',
]
with open('backend/routers/phonesoftware/tenants.py','w',encoding='utf-8') as f:
    f.write('\n'.join(lines))
import subprocess,sys
r=subprocess.run([sys.executable,'-m','py_compile','backend/routers/phonesoftware/tenants.py'],capture_output=True,text=True)
print('Syntax:','OK' if r.returncode==0 else r.stderr)
